-- Create RSVP table
create table public.rsvp (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  guests integer default 1,
  status text not null
);

-- Create Wishes table
create table public.wishes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  message text not null
);

-- Enable Realtime for Wishes
alter publication supabase_realtime add table wishes;
